/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2013-05-22 06:20:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import bugreporter.*;
import login.*;
import bugreporter.*;

public final class bugreports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon1.gif\" type=\"image/x-icon\" /> \r\n");
      out.write("<LINK rel=\"stylesheet\" href=\"Style.css\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/* <![CDATA[ */\r\n");
      out.write("   function toggleVisibility(controlId)\r\n");
      out.write("        {\r\n");
      out.write("            var control = document.getElementById(controlId);\r\n");
      out.write("            if(control.hidden == true)\r\n");
      out.write("                control.hidden = false;\r\n");
      out.write("            else if(control.hidden==false) \r\n");
      out.write("                control.hidden = true;\r\n");
      out.write("              \r\n");
      out.write("        };\r\n");
      out.write("  var a = 0;\r\n");
      out.write("  function toggle2 ()\r\n");
      out.write("  {\r\n");
      out.write("\talert(\"togle2\");\r\n");
      out.write("  };\r\n");
      out.write("  function test()\r\n");
      out.write("  {\r\n");
      out.write("\t  for( var i=0;i<5;i++)\r\n");
      out.write("\t  alert(\"tesT\");\r\n");
      out.write("  };\r\n");
      out.write("/* ]]> */\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Bug Reports</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#EBE6E5\">\r\n");
      out.write("  ");
 String getURL=request.getRequestURL().toString();
	session.setAttribute("currentURL",getURL); 
	
      out.write("\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write(" ");
 
if(session.getAttribute("currentSessionUser")!=null){
User currentUser = (User)(session.getAttribute("currentSessionUser"));
out.println("Hello, <a href = 'Userprofile?name="+currentUser.getNickname()+"'>"); 
out.println(currentUser.getNickname()+"</a>!" ); 

out.println("<INPUT  Style='color:white;background-color:black; position:relative; left:700px;border-radius: 5px;-moz-border-radius:5px;'  Value = 'Logout' onClick=\"window.location='logout' \" TYPE='SUBMIT'>");
}
else 
	out.println("<INPUT  Style='color:white;background-color:black;border-radius: 5px;-moz-border-radius:5px;'  Value = 'Login' onClick=\"window.location='login.jsp' \" TYPE='SUBMIT'>");

      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("<a href=\"ViewMain.jsp\"><img src=\"home.jpg\" width=\"40\" height=\"40\" border=\"2\" style='position:relative;left:800px;border-radius: 35px;-moz-border-radius:35px;border: 3px black solid;'/></a>\r\n");
      out.write("\r\n");
      out.write("<h1 align = 'center'>Bug Reports</h1>\r\n");
      out.write("\r\n");
      out.write("<FORM METHOD=POST ACTION=\"SearchBugList\">\r\n");
      out.write("<table align='center' border=1 border=\"black\" cellpadding=\"5\" id = \"sumtable\"  RULES=NONE FRAME=BOX style='border: 1px solid black;border-radius: 10px;-moz-border-radius:10px; border-style: solid; background-color: #000000;'>\r\n");
      out.write("<tr style='font-family: Arial;font-size: 10pt;background-color: #C3BEBD'><th>Status/Assigned to</th><th>Owner</th><th>Test Engineer</th><th>Manufacturing Engineer</th><th>MFG</th><th>Programmer</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

BugSumTable tablefetcher = new BugSumTable();
Table table = tablefetcher.GetTable();

for(int i=0;i<3;i++)
{	
	out.println("<tr style='font-family: Arial;font-size: 10pt;background-color: #C3BEBD'>");
	out.println("<td>");
	if(i==0)
		out.println("Open");
	if(i==1)
		out.println("Urgent");
	if(i==2)
		out.println("Closed");
	out.println("</td>");
	for(int j=0;j<5;j++)
	{	out.println("<td align='center'>");
		out.println("<input type='submit' style='background-color:#C3BEBD;border-width:0px;'  name='button"+i+j+"'class='link' value ='"+table.getValue(i, j)+"'/>");
		//out.println(table.getValue(i, j));		
		out.println("</td>");
	}
	out.println("</tr>");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</FORM>\r\n");
      out.write("<h2 align = 'center'>Bugs</h2>\r\n");
      out.write("<button hidden='true'  onclick='test()'>test</button>\r\n");


 BugList bugList = new BugList();
 ArrayList<Bug> bl = new ArrayList<Bug>();
 bl = bugList.getBugList();
for(int i=0;i<bl.size();i++)
{
	out.println("<div id='bugtitle"+i+"'>");
	out.println("<div class = 'comment'><br/><div class='line' style='color:grey;'></div>");
	out.println("<span class='bubble'><button style='background-color:#EBE6E5;border-width:0px;' onclick="+"\"toggleVisibility('bug"+i+"')\"><img height='25' width='25' src='toggle-expand.png'/></button>");
	out.println("<FORM METHOD=POST ACTION='ChangeBug' style='display:inline;'>");
	String tempUrl= "<a href = 'Userprofile?name="+bl.get(i).getFiler()+"'>"+bl.get(i).getFiler()+"</a>"; 
	out.println("<b>"+bl.get(i).getName()+"</b > | Assigned to <b>: "+bl.get(i).getAssignee()+"</b> | Filed by <b>:"+tempUrl+"</b> | Status : <b>"+bl.get(i).getSatus()+"</b>");
	
	if(session.getAttribute("currentSessionUser")!=null)
	{
		User currentUser = (User)(session.getAttribute("currentSessionUser"));
		if(currentUser.getNickname().equals("admin")||currentUser.getNickname().equals(bl.get(i).getFiler()))
			out.println("<INPUT TYPE='submit' style='background-image: url(delete.png);position:absolute;left:950px;border: none'  HEIGHT='20' WIDTH='20' value='' BORDER='0'  id = 'deletebug"+i+"'  name = 'deletebug"+i+"'>");
	}
	out.println("</span>");
	out.println("</span></div>");
	if(i==bl.size()-2)
		out.println("<div id='bug"+i+"' hidden='true'><span class='bubble'>");
	else 
		out.println("<div id='bug"+i+"' hidden = 'false'><span class='bubble'>");
	out.println("<br/><b>Description : </b>");
	out.println(bl.get(i).desc());
	out.println("<br/><br/>");
	out.println("<b>Re-assign to : </b><select name ='assignee"+i+"'>	<option value='none'>None</option><option value='Owner'>Owner</option>	<option value='TestEng'>Test Engineer</option>	<option value='ME'>Manufacturing Engineer</option><option value='MFG'>MFG</option><option value='Programer'>Programmer</option></select><br/>");
	out.println("<b>Change Status to : </b><input name = 'status"+i+"' type = 'radio' value = 'none'>Do no change</input><input name = 'status"+i+"' type = 'radio' value = 'open'>Open</input><input name = 'status"+i+"' type = 'radio' value = 'closed'>Closed</input><input name = 'status"+i+"' type = 'radio' value = 'urgent'>Urgent</input>");
	out.println("<INPUT TYPE='SUBMIT' value ='Submit Change' name = 'submitchange"+i+"'>");
	out.println("</form><br/><b>Comments :</b><br/><div class='line' style='color:grey;'>....................................................................................................</div><br/>");
	for(int j=0;j<bl.get(i).getComList().size();j++)
	{
		out.println("<b>"+bl.get(i).getComList().get(j).getName()+"</b> said <br/>"+bl.get(i).getComList().get(j).getContent());
		out.println("<br/></b><div class='line' style='color:grey;'>....................................................................................................</div><br/>");	
	}
	out.println("<br/><b>New Comment : </b>");
	out.println("<FORM METHOD=POST ACTION='AddCommentThread'>");
	  String temp1="";
	if(session.getAttribute("currentSessionUser")!=null){
	User currentUser = (User)(session.getAttribute("currentSessionUser"));
	// out.println(currentUser.getNickname()); 
	 temp1 = currentUser.getNickname();
	}
	
	out.println("</br><b>Name : </b><br/>"+temp1+"<input type='hidden' name ='name"+i+"' value ='"+temp1+"'/><br/><b>Comment : </b><br/><textarea name = 'comdesc"+i+"'></textarea><INPUT TYPE='SUBMIT' value ='Submit Comment' name = 'submitcom"+i+"'></form>");
	out.println("</span></div>");
	
}
//out.println("_______________________________________________<br/>");

      out.write(" \r\n");
      out.write("<br/><br/>\r\n");
if(session.getAttribute("currentSessionUser")!=null){
User currentUser = (User)(session.getAttribute("currentSessionUser"));
if(currentUser.getAccess()==1)
out.println("<div>");
else
out.println("<div hidden='true'>");
}
else
out.println("<div hidden='true'>");

      out.write("\r\n");
      out.write("<FORM METHOD=POST ACTION=\"SaveBuglist\"><span class='bubble'>New Bug : <br/>\r\n");
      out.write("Title: \r\n");
      out.write("<input type='text' name ='name'/>\r\n");
      out.write("<br/>\r\n");
      out.write("Your Name: \r\n");
 
String temp="";
if(session.getAttribute("currentSessionUser")!=null){
User currentUser = (User)(session.getAttribute("currentSessionUser"));
out.println("<a href = 'Userprofile?name="+currentUser.getNickname()+"'>"); 
out.println(currentUser.getNickname()+"</a>" ); 
 temp = currentUser.getNickname();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type='hidden' name ='Filer' value = ");
out.println("'"+temp+"'");
      out.write(" />\r\n");
      out.write("<br/>\r\n");
      out.write("Assigned to: <select name=\"assignee\">\r\n");
      out.write("<option value=\"Owner\">Owner</option>\r\n");
      out.write("<option value=\"TestEng\">Test Engineer</option>\r\n");
      out.write("<option value=\"ME\">Manufacturing Engineer</option>\r\n");
      out.write("<option value=\"MFG\">MFG</option>\r\n");
      out.write("<option value=\"Programer\">Programmer</option>\r\n");
      out.write("</select>\r\n");
      out.write("<br/>\r\n");
      out.write("Status <input name = 'status' type = 'radio' value = 'open' CHECKED='checked'>Open<input name = 'status' type = 'radio' value = 'closed'>Closed<input name = 'status' type = 'radio' value = 'urgent'>Urgent\r\n");
      out.write("<br/>\r\n");
      out.write("Description\r\n");
      out.write("<textarea name = 'Bug'>\r\n");
      out.write("</textarea>\r\n");
      out.write("<input type=\"hidden\" name=\"MAX_FILE_SIZE\" value=\"500\" />\r\n");
      out.write("<INPUT TYPE='SUBMIT' value ='Submit Bug'><br><br>\r\n");
      out.write("<span style=\"font-size:15px;color:red\">All Info is required</span></span></form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
