/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2013-05-22 06:20:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon1.gif\" type=\"image/x-icon\" /> \r\n");
      out.write("<meta http-equiv=\"Content-Type\"\r\n");
      out.write("\tcontent=\"text/html; charset=windows-1256\">\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#EBE6E5\">\r\n");
      out.write("<input type=\"button\" Style=\"border:1px;width:1200px;background-color:#EBE6E5\">\r\n");
      out.write("<a href=\"ViewMain.jsp\"><img src=\"home.jpg\" width=\"40\" height=\"40\" border=\"2\" style='border-radius: 35px;-moz-border-radius:35px;border: 3px black solid;'/></a>\r\n");
      out.write("<div align = \"middle\">\r\n");
      out.write("<br><br><br><br><br><br><div style='font-family: Helvetica;font-size: 20pt;background-color: #EBE6E5;color:blue;'><b>Login</b></div>\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"LoginServlet\" method='post'>\r\n");
      out.write("\t\tIBM Id <input width=\"150\" style='border-radius: 5px;-moz-border-radius:5px;background-color:#F5F1F0;' type=\"text\" name=\"un\" /><br>\r\n");
      out.write("\t\t<br>Password <input width=\"150\" style='border-radius: 5px;-moz-border-radius:5px;background-color:#F5F1F0;' type=\"password\" name=\"pw\" /><br> \r\n");
      out.write("\t\t<br><input type=\"submit\" value=\"Submit\"  Style=\"height:30px;border-radius: 5px;-moz-border-radius:5px;background-color:#99CC33;\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
String allowed="";
	if(session.getAttribute("isValid")!=null)
		allowed = (session.getAttribute("isValid")).toString(); 
	if(allowed.equals("FAIL"))
		out.println("<br><div style='font-family: Arial;font-size: 10pt;color: red;'>Invalid Login</div>");
		session.setAttribute("isValid", null);
      out.write("\r\n");
      out.write("\t<br><br><br><br>\r\n");
      out.write("\tNew User?\r\n");
      out.write("\t<a href=\"signup.jsp\">Sign Up!</a>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
