/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2013-05-22 06:20:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DataBase1.*;
import java.io.*;

public final class View2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon1.gif\" type=\"image/x-icon\" /> \r\n");
      out.write("<title>Test Table</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<INPUT  Style=\"color:white;background-color:black;border-radius: 5px;-moz-border-radius:5px;\"  Value = \"View Chart for Data\" onClick=\"window.location='testchart.jsp' \" TYPE='SUBMIT'>\r\n");
      out.write("<a href=\"ViewMain.jsp\"><img src=\"home.jpg\" width=\"40\" height=\"40\" border=\"2\" style='position:relative;left:1200px;border-radius: 35px;-moz-border-radius:35px;border: 3px black solid;'/></a>\r\n");
      out.write("<br><br>\r\n");
      out.write("<table border=1 cellpadding=5 style='border-radius: 10px;-moz-border-radius:10px; border-style: solid; border-color: #000000; padding:10; background-color: #D7D3D2; margin-left:auto; margin-right:auto;' >\r\n");
      out.write("<tr style='border-radius: 10px;-moz-border-radius:10px;' ><th>Order No<th>Test Cell</th><th>Test Time</th><th>MACHMOD</th><th>MACHSER</th><th>Title</th><th>Status Time</th><th>Start Time</th><th>UserName</th></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 


table Table = TestTable.startExec();
int rsize = Table.getRows();
int csize = Table.getColumns();

for(int i=1;i<rsize;i++)
{   
	out.println("<tr style='border-radius: 5px;-moz-border-radius:5px;background-color:#F5F1F0;'>");
    for(int j=0;j<csize;j++)
    {
    	
            out.println("<td style='border-radius: 5px;-moz-border-radius:5px;background-color:#F5F1F0;'>");
        out.println(Table.getValue(i,j));
        out.println("</td>");
        }
    }
out.println("</tr>");
    

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
